name: FinPhaser
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - r-base=3.6.3
  - ancestry_hmm=1.0.2
  - selam=0.9
  - bcftools=1.14
  - htslib=1.21
  - gsl=2.7
  - pandas
  - numpy
  - python-dateutil
  - r-ggplot2
  - r-dplyr
  - r-data.table
  - r-tidyr
  - r-readr
  - r-r.utils
  - pip
  - pip:
    - -e .