#!/usr/bin/env python3
"""
bin/generate_spore_settings.py
================================
Generates a complete SPORE-Settings.R from samples.yml and runtime paths.

Writes every variable that SPORE.R reads, matching the full settings file
format used in the working manual runs.

Key decisions made here:
  - `folder` is set to the Nextflow process working directory (passed
    as --workdir). SPORE expects folder to end with "/".
  - `vcf` is just the filename (not a path) because SPORE constructs
    the full path as paste0(folder, vcf).
  - `Genomics_Sex_File` is the absolute path to the TSV written by
    yaml_to_sex_tsv.py (underscores preserved — matches VCF names).
  - `trufflepath` comes from spore.truffle_path in samples.yml,
    resolved relative to cwd (repo root during a Nextflow run).
  - All other parameters come from the spore: block of samples.yml.

No pyyaml dependency — uses stdlib-only parsing.

Usage (called automatically by Nextflow — not normally run directly):
    python bin/generate_spore_settings.py \\
        --vcf-filename  YHPed1_conserved_phased.vcf.gz \\
        --workdir       /path/to/nextflow/workdir/ \\
        --sex-tsv       /abs/path/Genomics_Sex.tsv \\
        --samples-yml   config/samples.yml \\
        --out           SPORE-Settings.R
"""

import argparse
import sys
from pathlib import Path


def parse_spore_block(yml_path: Path) -> dict:
    """
    Parse only the spore: block from samples.yml.
    Returns a flat dict of key → value (all as strings).
    Strips inline YAML comments from values.
    """
    text = yml_path.read_text()
    spore = {}
    in_spore = False

    for raw_line in text.splitlines():
        line = raw_line.strip()

        if line == "spore:":
            in_spore = True
            continue

        # Stop at next top-level key
        if in_spore and line and not line.startswith("#"):
            indent = len(raw_line) - len(raw_line.lstrip())
            if indent == 0 and ":" in line:
                in_spore = False
                continue

        if not in_spore or not line or line.startswith("#"):
            continue

        if ":" in line:
            k, v = line.split(":", 1)
            # Strip inline comments before parsing value
            # e.g. '""  # leave empty if no birthdates' → ''
            v_clean = v.split("#")[0].strip().strip('"').strip("'")
            spore[k.strip()] = v_clean

    return spore


def r_bool(val: str) -> str:
    """Convert Python/YAML boolean strings to R TRUE/FALSE."""
    if str(val).upper() in ("TRUE", "YES", "1"):
        return "TRUE"
    return "FALSE"


def r_str(val: str) -> str:
    """Wrap a value in R double quotes."""
    return f'"{val}"'


def parse_args():
    p = argparse.ArgumentParser(description="Generate complete SPORE-Settings.R")
    p.add_argument("--vcf-filename", required=True,
                   help="The compressed VCF filename (not a path) — SPORE builds full path as folder+vcf")
    p.add_argument("--workdir",      required=True,
                   help="Absolute path to Nextflow process working directory (becomes `folder`)")
    p.add_argument("--sex-tsv",      required=True,
                   help="Absolute path to Genomics_Sex.tsv")
    p.add_argument("--samples-yml",  required=True,
                   help="Path to samples.yml")
    p.add_argument("--out",          default="SPORE-Settings.R",
                   help="Output settings file name")
    return p.parse_args()


def main():
    args = parse_args()

    yml_path = Path(args.samples_yml)
    if not yml_path.exists():
        sys.exit(f"ERROR: samples.yml not found: {yml_path}")

    spore = parse_spore_block(yml_path)

    # Validate required keys
    required = ["truffle_path", "truffle_maf", "truffle_missing", "APO",
                "max_memory", "max_cores", "output_label"]
    missing = [k for k in required if k not in spore]
    if missing:
        sys.exit(f"ERROR: Missing keys in spore: block of samples.yml: {missing}")

    # Resolve truffle path — try relative to cwd first (repo root during Nextflow run)
    truffle_raw  = spore["truffle_path"]
    truffle_path = Path(truffle_raw)
    if not truffle_path.is_absolute():
        cwd_candidate = (Path.cwd() / truffle_raw).resolve()
        yml_candidate = (yml_path.parent.parent / truffle_raw).resolve()
        if cwd_candidate.exists():
            truffle_path = cwd_candidate
        elif yml_candidate.exists():
            truffle_path = yml_candidate
        else:
            truffle_path = cwd_candidate  # best guess even if missing

    if not truffle_path.exists():
        print(
            f"[generate_spore_settings] WARNING: truffle binary not found at "
            f"{truffle_path}. Ensure it exists and is executable.",
            file=sys.stderr,
        )

    # Ensure folder path ends with /
    workdir = args.workdir.rstrip("/") + "/"

    settings = f"""\
# SPORE-Settings.R
# Auto-generated by FinPhaser pipeline (bin/generate_spore_settings.py)
# Do not edit manually — regenerated on each pipeline run.
# Source: config/samples.yml  [spore:] block

# ── TRUFFLE executable ────────────────────────────────────────────────────────
trufflepath={r_str(truffle_path)}

# ── TRUFFLE filters ───────────────────────────────────────────────────────────
truffle_maf={spore["truffle_maf"]}
truffle_missing={spore["truffle_missing"]}

# ── SPORE sensitivity ─────────────────────────────────────────────────────────
APO={spore["APO"]}

# ── Sampling mode ─────────────────────────────────────────────────────────────
IntermediateSamplingMode={r_bool(spore.get("intermediate_sampling_mode", "FALSE"))}

# ── Memory / parallelism ──────────────────────────────────────────────────────
max_memory={r_str(spore["max_memory"])}
max_cores={spore["max_cores"]}
trufflecpu=max_cores

# ── Input files ───────────────────────────────────────────────────────────────
folder={r_str(workdir)}
vcf={r_str(args.vcf_filename)}

# Sex metadata — sample names match VCF exactly (underscores preserved)
Genomics_Sex_File={r_str(Path(args.sex_tsv).resolve())}

# Birthdate file — empty string if not available
Birthdate_File=""

# ── Output settings ───────────────────────────────────────────────────────────
pedigree_file_add_name=""
plots={r_bool(spore.get("plots", "TRUE"))}

# ── Filtering thresholds ──────────────────────────────────────────────────────
min_loci={spore.get("min_loci", "1")}
IBD2_DP_Threshold={spore.get("IBD2_DP_threshold", "0.95")}
downsample_for_homozygous_mendel={spore.get("downsample_for_homozygous_mendel", "1")}

# ── Advanced: disable SPORE variables ─────────────────────────────────────────
no_IBD0={r_bool(spore.get("no_IBD0", "FALSE"))}
no_IQR={r_bool(spore.get("no_IQR", "FALSE"))}
# no_HM is always TRUE — Mendelian trio errors require a known pedigree
# which is not available in this pipeline
no_HM=TRUE

# ── Optional extra variables file ─────────────────────────────────────────────
ExtraVariables={r_str(spore.get("extra_variables", "none"))}

# ── Advanced: resume previous partial run ────────────────────────────────────
previously_computed={r_bool(spore.get("previously_computed", "FALSE"))}
previously_computed_homozygous_mendel={r_bool(spore.get("previously_computed_homozygous_mendel", "FALSE"))}
previously_computed_mendel={r_bool(spore.get("previously_computed_mendel", "FALSE"))}
previously_computed_three_thresholds={r_bool(spore.get("previously_computed_three_thresholds", "FALSE"))}
"""

    Path(args.out).write_text(settings)
    print(f"[generate_spore_settings] Wrote {args.out}")


if __name__ == "__main__":
    main()